# Generated by Django 4.2 on 2023-04-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfile',
            name='generated_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
