# Generated by Django 4.2 on 2023-04-26 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processedfile_generated_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
